JWT_SECRET: ""
JWT_ALGORITHM: HS256"
ACCESS_TOKEN_EXPIRE_MINUTES: 60

host: 0.0.0.0
port: 8080
# quantity of workers for uvicorn
workers_count: 1
# Enable uvicorn reloading
reload: False

# Current environment
environment: dev

users_secret:
# Variables for the database
db_host: 127.0.0.1
db_port: 5432
db_user: postgres
db_pass: pass
db_base: auditrol_db
db_echo: False
cookie_domain: localhost
GOOGLE_CLIENT_ID:
GOOGLE_CLIENT_SECRET:
CACHE_MAXSIZE: 200
CACHE_TIMEOUT_HOUR: 12
FAILED_LOGIN_ROUTE: http://localhost:3000/
REDIRECT_CALLBACK_URL: http://localhost:8000/api/v1/auth/call
REDIRECT_LOGIN_URL: http://localhost:3000/redirect
CORS_ORGIN: [
    "http://localhost",
    "http://localhost:3000",
    "http://localhost:3000/redirect",
    "http://localhost:8080",
    "*.auditrol.net",
]