# Use the official Python 3.12 image
FROM python:3.10.0-slim

# Set the working directory inside the container
WORKDIR /app

# Update and install necessary packages
RUN apt-get update && apt-get install -y nano && apt-get clean

RUN apt-get update && apt-get install -y libgl1 libglib2.0-0


# Copy the application files to the container
COPY . .

# Install Poetry
RUN pip install poetry

# Install dependencies using Poetry
RUN poetry install 

# Expose the application port
EXPOSE 8080

# Define the command to run the application
CMD ["poetry", "run", "python", "-m", "backend"]
